# Generated by Django 3.0 on 2019-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('toUser', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('comment_text', models.CharField(max_length=250)),
                ('comment_date', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.CharField(max_length=100)),
                ('fromUser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('isClose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('uniqueid', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('view', models.IntegerField()),
                ('detail', models.IntegerField()),
                ('borrow', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('search', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemBorrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=100)),
                ('return_date', models.CharField(max_length=100)),
                ('taking_date', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('is_returned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=100)),
                ('request_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('notification_text', models.CharField(max_length=200)),
                ('notification_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('vn', models.CharField(max_length=6)),
                ('isv', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='WatchersForAddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcher', models.CharField(max_length=100)),
                ('watched', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
